### ISSUE TITLE
Core 3 still has 15% usage after Thread Optimizer

### ISSUE THREAD

**Issue by Doredialilligan** [GrapheneCt/CoreUnlocker80000H#1]
After setting up everything an giving every thread core 3 affinity, core 3 still has a usage between 10-15% on Blue Reflection.

Could this be a bug or just the game not developed to use that core?

**Comment by GrapheneCt** [comment]
That means the main thread of the game does most of the work. For now there is no way to change it's parameters.

Also this issue doesn't belong here. Please post stuff related to TO on it's page.
